### ISSUE TITLE
Extrenal bibliotek saknas

### ISSUE THREAD

**Issue by ecspresso** [Eitraz/swedbank-api#1]
Din kod kräver SLF4J men jag ser inget om detta i README.

**Comment by ecspresso** [comment]
Här är allt som saknades:
Apache Commons IO, lang3
FasterXML Jackson Annotations, core, databind
Lombok
SLF4J

**Comment by Eitraz** [comment]
commons, io och jackson ligger med i POM - lombok är dock med scope provided. Möjligt att någon dependency drar in SLF4j, men i koden används logback
