### ISSUE TITLE
Unable to pull transactions

### ISSUE THREAD

**Issue by ecspresso** [Eitraz/swedbank-api#2]
Using your first example, I get the following error:

```
com.github.eitraz.swedbank.exception.SwedbankClientException: POST request for https://online.swedbank.se/TDE_DAP_Portal_REST_WEB/api/v5/identification/bankid/mobile?dsid=TXFMgFAfkXIEaSrF failed with status 400 and body: {"errorMessages":{"general":[{"code":"BankIdOnSameDeviceAttributeNotProvided","message":"Det gick inte att logga in. Din klient skickade inte in valet om BankID finns installerad på detta enhet eller ej."}],"fields":[{"field":"bankIdOnSameDevice","message":"Valet av enhet för BankID angavs ej."}]}}
    at com.github.eitraz.swedbank.SwedbankClient.doRequest(SwedbankClient.java:183)
    at com.github.eitraz.swedbank.SwedbankClient.post(SwedbankClient.java:63)
    at com.github.eitraz.swedbank.authentication.MobileBankId.authenticate(MobileBankId.java:33)
    at Main.main(Main.java:23)
```

So I changed `AuthenticationRequest.java` and added `private boolean bankIdOnSameDevice;` to the class and `loginRequest.setBankIdOnSameDevice(false);` to the method.

I looked at the requests in the browser and it also sets `bankIdOnSameDevice` in the body of the request, but in the browser I need to scan the image that appears afterwards with my BankId.

This is the result after changing the code:

```
com.github.eitraz.swedbank.exception.SwedbankAuthenticationException: Unable to use Mobile BankID. It may have to be activated at swedbank.se.
	at com.github.eitraz.swedbank.authentication.MobileBankId.authenticate(MobileBankId.java:40)
	at Main.main(Main.java:23)
```

Is this possible to solve?

**Comment by Eitraz** [comment]
Tja!

Var tyvärr rätt länge sedan jag titta på/använde den här koden - ca 3 år - så det har nog hänt en del med Swedbanks inloggning. De har ju bland annat lagt till att man måste scanna en QR-kod som man inte behövde göra tidigare. Ser ut att vara det problemet du har stött på.

Jag har inga planer på att uppdatera det här just nu tyvärr, men det är bara att klona och hacka på om du vill :)

MVH,
Petter

**Comment by ecspresso** [comment]
Tack för svaret, jag misstänkte att det inte var ett aktuellt projekt längre eftersom att det var så länge sedan.
